name: ChatOps Action
description: Enables ChatOps in your GitHub repositories.
author: João Cerqueira

inputs:
  token:
    required: false
    description: A Personal Access Token to be used in every request to GitHub

  project:
    required: false
    description: The project's name

  processor:
    required: false
    description: The repository to where commands will be dispatched to

  environments:
    required: false
    description: A list of environments the project has

runs:
  using: 'node12'
  main: 'dist/index.js'
