name: Deploy

on:
  repository_dispatch:
    types: [chatops-deploy]

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ github.token }}
          event: deployment-pending
          payload: ${{ toJSON(github.event.client_payload) }}

  start:
    runs-on: ubuntu-latest
    needs: boot
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ github.token }}
          event: deployment-in-progress
          payload: ${{ toJSON(github.event.client_payload) }}

  finish:
    runs-on: ubuntu-latest
    needs: finish
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.CHATOPS_TOKEN }}
          event: deployment-success
          payload: ${{ toJSON(github.event.client_payload) }}
