name: Deploy

on:
  repository_dispatch:
    types: [chatops-deploy]

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ github.token }}
          event: deployment-pending
          context: ${{ github.event.client_payload }}

  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ github.token }}
          event: deployment-in-progress
          context: ${{ github.event.client_payload }}

  finish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.CHATOPS_TOKEN }}
          event: deployment-success
          context: ${{ github.event.client_payload }}
